<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="images/book_cover.jpg" width="120">

*This notebook contains an excerpt from the [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), the content is also available at [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*The copyright of the book belongs to Elsevier. We also have this interactive book online for a better learning experience. The code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work on [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) or [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

# Solutions for Problems in Chapter 2

In [1]:
import numpy as np

1. Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x. 

In [2]:
x = 2
y = 3
del x

2. Write a line of code that generates the following error:
```
NameError: name 'x' is not defined
```

In [3]:
x

NameError: name 'x' is not defined

3. Let x = 10 and y = 3. Write a line of code that will make each of the following assignments.

```
u = x + y
v = xy
w = x/y
z = sin(x)
r = 8sin(x) 
s = 5sin(xy)
p = x**y
```

In [4]:
x = 10
y = 3
u = x + y
v = x*y
w = x/y
z = np.sin(x)
r = 8*np.sin(x) 
s = 5*np.sin(x*y)
p = x**y

4. Show all the variables in the Jupyter notebook after you finish problem 3.

In [5]:
%who

np	 p	 r	 s	 u	 v	 w	 x	 y	 
z	 


5. Assign string '123' to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the *type* function. 

In [6]:
S = '123'
N = float(S)
print(f'S is {type(S)}, N is {type(N)}')

S is <class 'str'>, N is <class 'float'>


6. Assign the string 'HELLO' to the variable s1 and the string 'hello' to the variable s2. Use the *==* operator to show that they are not equal. Use the *==* operator to show that s1 and s2 are equal if the *lower* method is used on s1. Use the **==** operator to show that s1 and s2 are equal if *upper* method is used on s2. 

In [7]:
s1 = 'HELLO'
s2 = 'hello'

s1 == s2

False

In [8]:
s1.lower() == s2

True

In [9]:
s1 == s2.upper()

True

7. Use the *print* function to generate the following strings. 
* The word 'Engineering' has 11 letters. 
* The word 'Book' has 4 letters.



In [10]:
engineering = 'Engineering'
book = 'Book'
print(f"The word {engineering} has {len(engineering)} letters")
print(f"The word {book} has {len(book)} letters")

The word Engineering has 11 letters
The word Book has 4 letters


8. Check if 'Python' is in 'Python is great!'. 

In [11]:
'Python' in 'Python is great!'

True

9. Get the last word 'great' from 'Python is great!'

In [12]:
'Python is great!'[-6:-1]

'great'

10. Assign list [1, 8, 9, 15] to a variable *list_a* and insert 2 at index 1 using the *insert* method. Append 4 to the *list_a* using the *append* method. 

In [13]:
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
print(list_a)

list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15]
[1, 2, 8, 9, 15, 4]


11. Sort the *list_a* in problem 10 in ascending order. 

In [14]:
list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


12. Turn 'Python is great!' to a list. 

In [15]:
'Python is great!'.split()

['Python', 'is', 'great!']

13. Create one tuple with element 'One', 1 and assign it to tuple_a

In [16]:
tuple_a = ('one', 1)

14. Get the 2nd element in the tuple_a in problem 13. 

In [17]:
tuple_a[1]

1

15. Get the unique element from (2, 3, 2, 3, 1, 2, 5). 

In [18]:
set((2, 3, 2, 3, 1, 2, 5))

{1, 2, 3, 5}

16. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Get the following:
    * union of set_a and set_b
    * intersection of set_a and set_b
    * difference of set_a to set_b using *difference* method

In [19]:
set_a = {2, 3, 2}
set_b = {1, 2, 3}

set_a.union(set_b)

{1, 2, 3}

In [20]:
set_a.intersection(set_b)

{2, 3}

In [21]:
set_b.difference(set_a)

{1}

17. Create a dictionary that has the keys 'A', 'B', 'C' with values 'a', 'b', 'c' individually. Print all the keys in the dictionary. 

In [22]:
dict_abc = {'A':'a', 'B':'b', 'C':'c'}
print(list(dict_abc.keys()))

['A', 'B', 'C']


18. Check if key 'B' is in the dictionary defined in problem 17. 

In [23]:
'B' in dict_abc

True

19. Create array x and y, where  x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3.

In [24]:
x = np.array([1, 4, 3, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])

u = x + y
v = x*y
w = x/y
z = np.sin(x)
r = 8*np.sin(x) 
s = 5*np.sin(x*y)
p = x**y

20. Generate an array with size 100 evenly spaced between -10 to 10 using *linspace* function in Numpy.

In [25]:
np.linspace(-10, 10, 100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

21. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.

In [26]:
array_a = np.array([-1, 0, 1, 2, 0, 3])
array_a[array_a>0]

array([1, 2, 3])

22. Create an array $y = \begin{pmatrix} 
3 & 5 & 3 \\
2 & 2 & 5 \\
3 & 8 & 9 \\
\end{pmatrix}$ and calculate the transpose of the array. 

In [27]:
y = np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]])
y.T

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

23. Create a zero array with size (2, 4). 

In [28]:
zero_arr = np.zeros((2, 4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

24. Change the 2nd column in the above array to 1.  

In [29]:
zero_arr[:, 1, ...] = 1
zero_arr

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

25. Write a cell magic to clear all the variables in the Jupyter notebook

In [30]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [31]:
%who

Interactive namespace is empty.
