<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="images/book_cover.jpg" width="120">

*This notebook contains an excerpt from the [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), the content is also available at [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*The copyright of the book belongs to Elsevier. We also have this interactive book online for a better learning experience. The code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work on [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) or [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

# Solutions for Problems in Chapter 4

In [1]:
import numpy as np

1. Write a function `my_tip_calc(bill, party)`, where `bill` is the total cost of a meal and `party` is the number of people in the group. The tip should be calculated as 15% for a party strictly less than six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party 11 or more. A couple of test cases are given below. 

In [2]:
def my_tip_calc(bill, party):
        
    if party < 6:
        tips = 0.15 * bill
    elif party < 8:
        tips = 0.18 * bill
    elif party < 11:
        tips = 0.2 * bill
    elif party >= 11:
        tips = 0.25 * bill
    
    return tips

In [3]:
# t = 16.3935
t = my_tip_calc(109.29,3) 
print(t)

16.3935


In [4]:
# t = 19.6722
t = my_tip_calc(109.29,7) 
print(t)

19.6722


In [5]:
# t = 21.8580
t = my_tip_calc(109.29,9)
print(t)

21.858000000000004


In [6]:
# t = 27.3225
t = my_tip_calc(109.29,12)
print(t)

27.3225


2. Write a function `my_mult_operation(a,b,operation)`. The input argument, `operation`, is a string that is either `'plus'`, `'minus'`, `'mult'`, `'div'`, or `'pow'`, and the function should compute: $a+b$, $a-b$, $a∗b$, $a/b$, and $a^b$ for the respective values for `operation`. A couple of test cases are given below. 

In [7]:
def my_mult_operation(a,b,operation):
    
    if operation == 'plus':
        out = a + b
    elif operation == 'minus':
        out = a - b
    elif operation == 'mult':
        out = a * b
    elif operation == 'div':
        out = a / b
    elif operation == 'pow':
        out = a**b
    return out

In [8]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

In [9]:
# Output: [3,5,7,9]
my_mult_operation(x,y,'plus')

array([3, 5, 7, 9])

In [10]:
# Output: [-1,-1,-1,-1]
my_mult_operation(x,y,'minus')

array([-1, -1, -1, -1])

In [11]:
# Output: [2,6,12,20]
my_mult_operation(x,y,'mult')

array([ 2,  6, 12, 20])

In [12]:
# Output: [0.5,0.66666667,0.75,0.8]
my_mult_operation(x,y,'div')

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [13]:
# Output: [1,8,81,1024]
my_mult_operation(x,y,'pow')

array([   1,    8,   81, 1024])

3. Consider a triangle with vertices at $(0,0)$, $(1,0)$, and $(0,1)$. Write a function *my_inside_triangle(x,y)* where the output is the string 'outside' if the point $(x,y)$ is outside of the triangle, 'border' if the point is exactly on the border of the triangle, and 'inside' if the point is on the inside of the triangle.

In [14]:
def my_inside_triangle(x,y):
    """
    We can just compute the area of the triangle, and then we compute 
    the areas of the triangles formed by the point (x, y) and two of 
    the original triangle's vertices. If any of these formed triangles
    is 0, then it is on the board. If the sum of area the 3 formed
    triangles equals to the original triangle, it is inside, otherwise, 
    it is outside. 
    """
    x1, y1 = (0, 0)
    x2, y2 = (1, 0)
    x3, y3 = (0, 1)
    
    # A utility function to calculate area
    # of triangle formed by (x1, y1),
    # (x2, y2) and (x3, y3)
 
    def area(x1, y1, x2, y2, x3, y3):
        return abs((x1 * (y2 - y3) + x2 * (y3 - y1)
                + x3 * (y1 - y2)) / 2.0)
    
    A = area (x1, y1, x2, y2, x3, y3)
    A1 = area (x, y, x2, y2, x3, y3)
    A2 = area (x1, y1, x, y, x3, y3)
    A3 = area (x1, y1, x2, y2, x, y)
    
    if A1 == 0 or A2 ==0 or A3 == 0:
        return 'border'
 
    if(A == A1 + A2 + A3):
        return 'inside'
    else:
        return 'outside'

In [15]:
# Output: 'border'
my_inside_triangle(.5,.5)

'border'

In [16]:
# Output: 'inside'
my_inside_triangle(.25,.25)

'inside'

In [17]:
# Output: 'outside'
my_inside_triangle(5,5)

'outside'

4. Write a function *my_make_size10(x)*, where *x* is an array and output is the first 10 elements of *x* if *x* has more than 10 elements, and output is the array *x* padded with enough zeros to make it length 10 if *x* has less than 10 elements.

In [18]:
def my_make_size10(x):
    if len(x) > 10:
        size10 = x[:10]
    else:
        size10 = np.zeros(10)
        size10[:len(x)] = x
    
    return size10

In [19]:
# Output: [1,2,0,0,0,0,0,0,0,0]
my_make_size10(np.arange(1,3))

array([1., 2., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# Output: [1,2,3,4,5,6,7,8,9,10]
my_make_size10(np.arange(1,15))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Output: [3,6,13,4,0,0,0,0,0,0]
my_make_size10(np.array([3, 6, 13, 4]))

array([ 3.,  6., 13.,  4.,  0.,  0.,  0.,  0.,  0.,  0.])

5. Can you write my_make_size10 without using if-statements (i.e., using only logical and array operations)?

6. Write a function *my_letter_grader(percent)*, where grade is the string 'A+' if *percent* is greater than 97, 'A' if *percent* is greater than 93, 'A-' if *percent* is greater than 90, 'B+' if *percent* is greater than 87, 'B' if *percent* is greater than 83, 'B-' if *percent* is greater than 80, 'C+' if *percent* is greater than 77, 'C' if *percent* is greater than 73, 'C-' if *percent* is greater than 70, 'D+' if *percent* is greater than 67, 'D' if *percent* is greater than 63, 'D-' if *percent* is greater than 60, and 'F' for any *percent* less than 60. Grades exactly on the division should be included in the higher grade category.

In [22]:
def my_letter_grader(percent):
    # write your function code here
    
    if percent >= 97:
        grade = 'A+'
    elif percent >= 93:
        grade = 'A'
    elif percent >= 90:
        grade = 'A-'
    elif percent >= 87:
        grade = 'B+'
    elif percent >= 83:
        grade = 'B'
    elif percent >= 80:
        grade = 'B-'
    elif percent >= 77:
        grade = 'C+'
    elif percent >= 73:
        grade = 'C'
    elif percent >= 70:
        grade = 'C-'
    elif percent >= 67:
        grade = 'D+'
    elif percent >= 63:
        grade = 'D'
    elif percent >= 60:
        grade = 'D-'
    else:
        grade = 'F'
    
    return grade

In [23]:
# Output: 'A+'
my_letter_grader(97)

'A+'

In [24]:
# Output: 'B'
my_letter_grader(84)

'B'

7. Most engineering systems have redundancy. That is, an engineering system has more than is required to accomplish its purpose. Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. Write a function *my_nuke_alarm(s1,s2,s3)* where *s1*, *s2*, and *s3* are the temperature readings for sensor 1, sensor 2, and sensor 3, respectively. The output should be the string 'alarm!' if any two of the temperature readings disagree by strictly more than 10 degrees and 'normal' otherwise.

In [25]:
def my_nuke_alarm(s1,s2,s3):
    
    diff_12 = abs(s1 - s2)
    diff_23 = abs(s2 - s3)
    diff_13 = abs(s1 - s3)
    
    if diff_12 > 10 or diff_23 > 10 or diff_13 > 10:
        response = 'alarm'
    else:
        response = 'normal'
    
    return response

In [26]:
#Output: 'normal'
my_nuke_alarm(94,96,90)

'normal'

In [27]:
#Output: 'alarm!'
my_nuke_alarm(94,96,80)

'alarm'

In [28]:
#Output: 'normal'
my_nuke_alarm(100,96,90)

'normal'

8. Let Q(x) be the quadratic equation $Q(x) = ax^2 + bx + c$ for some scalar values *a*, *b*, and *c*. A root of $Q(x)$ is an *r* such that $Q(r) = 0$. The two roots of a quadratic equation can be described by the quadratic formula, which is

$$r = \frac{-b\pm\sqrt{b^2-4ac}}{2a}$$

A quadratic equation has either two real roots (i.e., $b^2 > 4ac$), two imaginary roots (i.e., $b^2 < 4ac$), or one root, $r = − \frac{b}{2a}$.

Write a function *my_n_roots(a,b,c)*, where *a*, *b*, and *c* are the coefficients of the quadratic $Q(x)$, the function should return two values: *n_roots* and *r*. *n_roots* is 2 if *Q* has two real roots, 1 if *Q* has one root, −2 if *Q* has two imaginary roots, and *r* is an array containing the roots of *Q*.

In [29]:
import cmath
def my_n_roots(a,b,c):
    
    if b**2 > 4 * a * c:
        n_roots = 2
        r1 = (-b + np.sqrt(b**2 - 4 * a * c))/2/a
        r2 = (-b - np.sqrt(b**2 - 4 * a * c))/2/a
        r = [r1, r2]
    elif b**2 < 4 * a * c:
        n_roots = -2
        r1 = (-b + cmath.sqrt(b**2 - 4 * a * c))/2/a
        r2 = (-b - cmath.sqrt(b**2 - 4 * a * c))/2/a
        r = [r1, r2]
    else:
        n_roots = 1
        r = -b/2/a

    return n_roots, r

In [30]:
# Output: n_roots = 2, r = [3, -3]
n_roots, r = my_n_roots(1,0,-9)
print(n_roots, r)

2 [3.0, -3.0]


In [31]:
# Output: n_roots = -2, r = [-0.6667 + 1.1055i, -0.6667 - 1.1055i]
my_n_roots(3,4,5)

(-2,
 [(-0.6666666666666666+1.1055415967851332j),
  (-0.6666666666666666-1.1055415967851332j)])

In [32]:
# Output: n_roots = 1, r = [-1]
my_n_roots(2,4,2)

(1, -1.0)

9. Write a function *my_split_function(f,g,a,b,x)*, where *f* and *g* are handles to functions $f(x)$ and $g(x)$, respectively. The output should be $f(x)$ if $x≤a$, $g(x)$ if $x≥b$, and $0$ otherwise. You may assume that $b>a$.

In [33]:
def my_split_function(f,g,a,b,x):
    
    if x<=a:
        return f(x)
    elif x>=b:
        return g(x)
    else:
        return 0

In [34]:
# Output: 2.713
my_split_function(np.exp,np.sin,2,4,1)

2.718281828459045

In [35]:
# Output: 0
my_split_function(np.exp,np.sin,2,4,3)

0

In [36]:
# Output: -0.9589
my_split_function(np.exp,np.sin,2,4,5)

-0.9589242746631385