<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="images/book_cover.jpg" width="120">

*This notebook contains an excerpt from the [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), the content is also available at [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*The copyright of the book belongs to Elsevier. We also have this interactive book online for a better learning experience. The code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work on [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) or [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

# Solutions for Problems in Chapter 3

In [1]:
import numpy as np

1. Recall that the hyperbolic sine, denoted by $\sinh$, is $\frac{\exp{(x)} - \exp{(-x)}}{2}$. Write a function $my\_sinh(x)$, where the output $y$ is the hyperbolic sine computed on $x$. Assume that _x_ is a 1 by 1 float.

In [2]:
my_sinh = lambda x: (np.exp(x) - np.exp(-x))/2
    
my_sinh(0)

0.0

In [3]:
my_sinh(1)

1.1752011936438014

In [4]:
my_sinh(2)

3.626860407847019

2. Write a function $my\_checker\_board(n)$, where the output $m$ is an $n\times n$ array with the following form:

    $$
    m =\begin{array}{ccccc}
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1
    \end{array}
    $$

 Note that the upper-left element should always be 1. Assume that _n_ is a strictly positive integer. 


In [5]:
def my_checker_board(n):
    
    x = np.ones((n, n))
    x[1::2,::2] = 0
    x[::2,1::2] = 0
    return x

In [6]:
my_checker_board(1)

array([[1.]])

In [7]:
my_checker_board(2)

array([[1., 0.],
       [0., 1.]])

In [8]:
my_checker_board(3)

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [9]:
my_checker_board(5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

3. Write a function $my\_triangle(b,h)$ where the output is the area of a triangle with base, _b_, and height, _h_. Recall that the area of a triangle is one-half the base times the height. Assume that _b_ and _h_ are just 1 by 1 float numbers.

In [10]:
def my_triangle(b, h):
    return b*h/2

my_triangle(1, 1)

0.5

In [11]:
my_triangle(2, 1)

1.0

In [12]:
my_triangle(12, 5)

30.0

4. Write a function $my\_split\_matrix(m)$, where $m$ is an array, the output is a list *[m1, m2]* where *m1* is the left half of *m*, and *m2* is the right half of *m*. In the case where there is an odd number of columns, the middle column should go to *m1*. Assume that *m* has at least two columns.

In [13]:
from math import ceil
def my_split_matrix(m):
    
    i, j = m.shape
    m1_c = ceil(j/2)    
    return [m[:, :m1_c], m[:, m1_c:]]

In [14]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
my_split_matrix(m)

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [15]:
m = np.ones((5, 5))
my_split_matrix(m)

[array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])]

5. Write a function $my\_cylinder(r,h)$, where *r* and *h* are the radius and height of a cylinder, respectively, and the output is a list *[s, v]* where *s* and *v* are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2\pi r^2 + 2\pi rh$, and the volume is $\pi r^2h$. Assume that *r* and *h* are 1 by 1 float.

In [16]:
def my_cylinder(r, h):
    s = 2*np.pi*r**2 + 2*np.pi*r*h
    v = np.pi*r**2*h
    return [s, v]

In [17]:
my_cylinder(1,5)

[37.69911184307752, 15.707963267948966]

In [18]:
my_cylinder(2,4)

[75.39822368615503, 50.26548245743669]

6. Write a function $my\_n\_odds(a)$, where *a* is a one-dimensional array of floats and the output is the number of odd numbers in *a*.

 Test Cases:

 ```python
 In: my_n_odds(np.arange(100))
 Out: 50
 
 In: my_n_odds(np.arange(2, 100, 2))
 Out: 0
 ```

In [19]:
def my_n_odds(a):
    n_odds = 0
    for num in a:
        if num%2 != 0:
            n_odds += 1
    return n_odds

In [20]:
my_n_odds(np.arange(100))

50

In [21]:
my_n_odds(np.arange(2, 100, 2))

0

7. Write a function $my\_twos(m,n)$, where the output is an $m\times n$ array of twos. Assume that *m* and *n* are strictly positive integers.

 Test Cases:

 ```python
 In: my_twos(3, 2)
 Out: array([[2, 2],
       [2, 2],
       [2, 2]])
 
 In: my_twos(1, 4)
 Out: array([2, 2, 2, 2])
 ```

In [22]:
def my_twos(m, n):
    return np.ones((m, n))*2

In [23]:
my_twos(3, 2)

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [24]:
my_twos(1, 4)

array([[2., 2., 2., 2.]])

8. Write a lambda function that takes in *x* and *y*, and output the value of *x - y*. 

In [25]:
sub = lambda x, y: x - y
sub(5, 3)

2

9. Write a function $add\_string(s1, s2)$, where the output is the concatenation of the strings *s1* and *s2*. 

 Test Cases:

 ```python
 In: s1 = add_string('Programming', ' ')
 In: s2 = add_string('is', 'fun!')
 In: add_string(s1, s2)
 Out: 'Programming is fun!'
 ```

In [26]:
def add_string(s1, s2):
    return s1 + s2

s1 = add_string('Programming', ' ')
s2 = add_string('is ', 'fun!')
add_string(s1, s2)

'Programming is fun!'

10. Generate the following errors:

    * TypeError: fun() missing 1 required positional argument: 'a'
    * IndentationError: expected an indented block

In [27]:
def fun(a):
    return a**2

fun()

TypeError: fun() missing 1 required positional argument: 'a'

In [28]:
def fun(a):
return a**2

IndentationError: expected an indented block (<ipython-input-28-fc74cf6d37ad>, line 2)

11. Write a function $greeting(name, age)$, where *name* is a string, *age* is a float, and the output is a string 'Hi, my name is XXX and I am XXX years old.' where XXX are the input name and age, respectively. 

In [29]:
def greeting(name, age):
    print(f'Hi, my name is {name} and I am {age} years old')

In [30]:
greeting('John', 26)

Hi, my name is John and I am 26 years old


In [31]:
greeting('Kate', 19)

Hi, my name is Kate and I am 19 years old


12. Let *r1* and *r2* be the radius of circles with the same center and let *r2>r1*. Write a function *my\_donut\_area(r1, r2)*, where the output is the area outside of the circle with radius *r1* and inside the circle with radius *r2*. Make sure that the function is vectorized. Assume that *r1* and *r2* are one-dimensional array of the same size. 

In [32]:
def my_donut_area(r1, r2):
    area1 = np.pi*r1**2
    area2 = np.pi*r2**2
    return area2 - area1

In [33]:
my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

array([ 9.42477796, 37.69911184, 84.82300165])

13. Write a function $my\_within\_tolerance(A, a, tol)$, where the output is an array or list of the indices in *A* such that  $|A-a| < \text{tol}$. Assume that *A* is a one-dimensional float list or array and that *a* and *tol* are 1 by 1 floats. 

In [34]:
def my_within_tolerance(A, a, tol):
    index = np.arange(len(A))
    out = index[np.abs(np.array(A) - a) < tol]
    return out

In [35]:
my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)

array([1, 2])

In [36]:
my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)

array([47, 48, 49, 50, 51, 52])

14. Write a function $bounding\_array(A, top, bottom)$, where the output is equal to the array *A* wherever *bottom < A < top*, the output is equal to *bottom* wherever *A <= bottom*, and the output is equal to *top* wherever *A >= top*. Assume that *A* is one-dimensional float array and that *top* and *bottom* are 1 by 1 floats. 

In [37]:
def bounding_array(A, top, bottom):
    out = []
    for num in A:
        if num <= bottom:
            tmp = bottom
        elif num >= top:
            tmp = top
        else:
            tmp = num
            
        out.append(tmp)
    return out

In [38]:
bounding_array(np.arange(-5, 6, 1), 3, -3)

[-3, -3, -3, -2, -1, 0, 1, 2, 3, 3, 3]