<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="images/book_cover.jpg" width="120">

*This notebook contains an excerpt from the [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), the content is also available at [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*The copyright of the book belongs to Elsevier. We also have this interactive book online for a better learning experience. The code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work on [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) or [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

# Solutions for Problems in Chapter 5

In [1]:
import numpy as np

1. What will the value of y be after the following code is executed?

In [2]:
y = 0
for i in range(1000):
    for j in range(1000):
        if i == j:
            y += 1
            
print(y)

1000


2. Write a function *my_max(x)* to return the maximum (largest) value in *x*. Don't use the built-in Python function *max*.

In [3]:
def my_max(x):
    max_v = x[0]
    for num in x[1:]:
        if num > max_v:
            max_v = num
    return max_v

In [4]:
my_max([-2, 4, -2, 3, 98, 2])

98

3. Write a function *my_n_max(x, n)* to return a list consisting of the n largest elements of *x*. You may use Python's *max* function. You may also assume that *x* is a one-dimensional list with no duplicate entries, and that *n* is strictly positive integer smaller than the length of *x* 

In [5]:
def my_n_max(x, n):
    
    x = sorted(x)
    out = x[-1:-n-1:-1]

    return out

In [6]:
# Output = [10, 9, 8]
x = [7, 9, 10, 5, 8, 3, 4, 6, 2, 1]
n = 3
out = my_n_max(x, n)
print(out)

[10, 9, 8]


4. Let *m* be a matrix of positive integers. Write a function *my_trig_odd_even(m)* to return an array *q*, where q[i, j] = sin (m[i, j]) if m[i, j] is even, and q[i, j] = cos (m[i, j]) if m[i, j] is odd.

In [7]:
def my_trig_odd_even(m):
    n, k = m.shape
    q = np.zeros(m.shape)
    for i in range(n):
        for j in range(k):
            if m[i, j]%2 ==0:
                q[i, j] = np.sin(m[i, j])
            else:
                q[i, j] = np.cos(m[i, j])
    return q

In [8]:
m = np.array([[3, 4, 4], [2, 1, 4]])
my_trig_odd_even(m)

array([[-0.9899925 , -0.7568025 , -0.7568025 ],
       [ 0.90929743,  0.54030231, -0.7568025 ]])

5. Let *P* be an $m \times p$ array and Q be a $p \times n$ array. As you will find later in this book, $M = P \times Q$ is defined as $M[i, j] = \sum_{k=1}^{p}P[i, k]\cdot Q[k, j]$. Write a function *my_mat_mult(P, Q) that uses for-loops to compute _M_, the matrix product of _P_ and _Q_. Hint: You may need up to three nested for-loops. Do not use the function *np.dot*.

In [9]:
import numpy as np

def my_mat_mult(P, Q):
    
    m, p = P.shape
    p, n = Q.shape
    
    M = np.zeros((m, n))
    
    for i in range(m):
        for j in range(n):
            v = 0
            for k in range(p):
                v += P[i, k]*Q[k, j]
            M[i, j] = v
    
    return M

In [10]:
# Output:
#  array([[3., 3., 3.],
#        [3., 3., 3.],
#        [3., 3., 3.]])

P = np.ones((3, 3))
my_mat_mult(P, P)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [11]:
# Output:
# array([[30, 30, 30],
#       [70, 70, 70]])

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
Q = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
my_mat_mult(P, Q)

array([[30., 30., 30.],
       [70., 70., 70.]])

6. The interest, $i$, on a principle, $P_0$, is a payment for allowing the bank to use your money. Compound interest is accumulated according to the formula $P_n = (1 + i)P_{n-1}$, where n is the compounding period, usually in months or years. Write a function *my_saving_plan(P0, i, goal)* where the output is the number of years it will take $P_0$ to become goal at $i\%$ interest compounded annually. 

In [12]:
def my_saving_plan(P0, i, goal):
    
    years = round(np.log(goal/P0)/np.log(1+i) + 1)
    
    return years

In [13]:
# Output: 15
my_saving_plan(1000, 0.05, 2000)

15.0

In [14]:
# Output: 11
my_saving_plan(1000, 0.07, 2000)

11.0

In [15]:
# Output: 21
my_saving_plan(500, 0.07, 2000)

21.0

7. Write a function with *my_find(M)*, where output is a list of indices *i* where M[i] is 1. You may assume that *M* is a list of only ones and zeros. Do not use the built-in Python function find.

In [16]:
def my_find(M):
    return [i for i, num in enumerate(M) if num==1]

In [17]:
# Output: [0, 2, 3]

M = [1, 0, 1, 1, 0]

my_find(M)

[0, 2, 3]

8. Assume you are rolling two six-sided dice, each side having an equal chance of occurring. Write a function *my_monopoly_dice()*, where the output is the sum of the values of the two dice thrown but with the following extra rule: if the two dice rolls are the same, then another roll is made, and the new sum added to the running total. For example, if the two dice show 3 and 4, then the running total should be 7. If the two dice show 1 and 1, then the running total should be 2 plus the total of another throw. Rolls stop when the dice rolls are different.

In [18]:
def roll():
    # note, the function randint the high is open, therefore, we use 7.
    return np.random.randint(1, 7, size=1)[0]

def my_monopoly_dice():
    running_total = 0
    count = 1
    while 1:
        dice_1 = roll()
        dice_2 = roll()
        
        running_total += dice_1 + dice_2
        
        print(f'Roll {count}:  dice_1 = {dice_1}, dice_2 = {dice_2}')
        if dice_1 != dice_2:
            break
            
        count += 1
        
    print(f'Running total = {running_total}')
    return running_total

In [19]:
running_total = my_monopoly_dice()

Roll 1:  dice_1 = 5, dice_2 = 1
Running total = 6


9. A number is prime if it is divisible without remainder only by itself and 1. The number 1 is not prime. Write a function *my_is_prime(n)*, where output is 1 if *n* is prime and 0 otherwise. Assume that *n* is a strictly positive integer.

In [20]:
def my_is_prime(n):
    if all(n % i for i in range(2, n)):
        out = 1
    else:
        out = 0
    return out

In [21]:
my_is_prime(17)

1

In [22]:
my_is_prime(8)

0

10. Write a function *my_n_primes(n)* where primes is a list of the first *n* primes. Assume that *n* is a strictly positive integer.

In [23]:
# Note, we need the function from problem 9. 
def my_n_primes(n):
    num = 2
    out = []
    while 1:
        if my_is_prime(num):
            out.append(num)
            
        if len(out) == n:
            break
        num += 1
            
    return out

In [24]:
my_n_primes(10)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

11. Write a function *my_n_fib_primes(n)*, where the output *fib_primes* is a list of the first *n* numbers that are both a Fibonacci number and prime. Note: 1 is not prime. Hint: Do not use the recursive implementation of Fibonacci numbers. A function to compute Fibonacci numbers is presented in Section 6.1. You may use the code freely.

In [25]:
# function from section 6.1
def fibonacci(n):
    """Computes and returns the Fibonacci of n, 
    a postive integer.
    """
    if n == 1: # first base case
        return 1
    elif n == 2: # second base case
        return 1
    else: # Recursive step
        return fibonacci(n-1) + fibonacci(n-2) # Recursive call 

def my_n_fib_primes(n):
    
    num = 4
    fib_primes = []
    while 1:
        
        fib = fibonacci(num)
        if my_is_prime(fib):
            fib_primes.append(fib)
            
        if len(fib_primes) == n:
            break
        num += 1
    return fib_primes

In [26]:
# Output: [3, 5, 13, 89, 233, 1597, 28657, 514229]

my_n_fib_primes(8)

[3, 5, 13, 89, 233, 1597, 28657, 514229]

In [27]:
# Output: [3, 5, 13]

my_n_fib_primes(3)

[3, 5, 13]

12. Write a function *my_trig_odd_even(M)*, where the output $Q[i, j] = sin (\pi/M[i, j])$ if $M[i,j]$ is odd, and $Q[i, j] = cos (\pi/M[i, j])$ if $M[i, j]$ is even. Assume that M is a two-dimensional array of strictly positive integers.

In [28]:
def my_trig_odd_even(M):
    n, k = M.shape
    Q = np.zeros(M.shape)
    for i in range(n):
        for j in range(k):
            if M[i, j]%2 ==0:
                Q[i, j] = np.cos(np.pi/M[i, j])
            else:
                Q[i, j] = np.sin(np.pi/M[i, j])
    return Q

In [29]:
# Output: [[0.8660, 0.7071], [0.8660, 0.4339]]
M = np.array([[3, 4], [6, 7]])
my_trig_odd_even(M)

array([[0.8660254 , 0.70710678],
       [0.8660254 , 0.43388374]])

13. Let $C$ be a square connectivity array containing zeros and ones. We say that point $i$ has a connection to point $j$ , or $i$ is connected to $j$ , if $C [i , j ] = 1$. Note that connections in this context are one-directional, meaning $C [i , j]$ is not necessarily the same as $C [ j , i ]$. For example, think of a one-way street from point A to point B. If A is connected to B, then B is not necessarily connected to A.

Write a function *my_connectivity_mat_2_dict(C, names)*, where *C* is a connectivity array and *names* is a list of strings that denote the name of a point. That is, *names[i]* is the name of the name of the *i-th* point. 

The output variable *node* should be a dict with the key as the string in *names* and value is a vector containing the indices, j, such that $C[i,j] = 1$. In other words, it is a list of points that point i is connected to.

In [30]:
def my_connectivity_mat_2_dict(C, names):
    node = {}
    C = np.array(C)
    for i, name in enumerate(names):
        node[name] = []
        for j in range(C.shape[1]):
            if C[i, j]:
                node[name].append(j+1)
    return node

In [31]:
C = [[0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1], [1, 1, 1, 0]]
names = ['Los Angeles', 'New York', 'Miami', 'Dallas']

In [32]:
# Output: node['Los Angeles'] = [2, 4]
#         node['New York'] = [1, 4]
#         node['Miami'] = [4]
#         node['Dallas'] = [1, 2, 3]

node = my_connectivity_mat_2_dict(C, names)
print(node)

{'Los Angeles': [2, 4], 'New York': [1, 4], 'Miami': [4], 'Dallas': [1, 2, 3]}


14. Turn the list *words* of lower case characters to upper case using list comprehension. 

In [33]:
words = ['test', 'data', 'analyze']

[word.upper() for word in words]

['TEST', 'DATA', 'ANALYZE']